const leaderboardData = [
  { team: 'Coders', points: '50' },
  { team: 'Phoenix', points: '30' },
  { team: 'Mavericks', points: '70' },
  { team: 'Innovators', points: '45' },
  { team: 'Builders', points: '20' },
  { team: 'Pioneers', points: '65' },
  { team: 'Titans', points: '15' },
  { team: 'Strategists', points: '40' },
  { team: 'Ninjas', points: '10' },
  { team: 'Gurus', points: '5' },
  { team: 'CodeHeroes', points: '25' },
  { team: 'TechLeaders', points: '80' },
  { team: 'FutureGeniuses', points: '55' },
  { team: 'DigitalNomads', points: '35' },
  { team: 'EpicCoders', points: '60' },
  { team: 'SuperCoders', points: '75' },
  { team: 'PowerPlayers', points: '90' },
  { team: 'CodeMasters', points: '100' },
  { team: 'EliteSquad', points: '85' },
  { team: 'ChampionCoders', points: '95' },
  { team: 'TechWizards', points: '110' },
  { team: 'DataDons', points: '120' },
  { team: 'ByteBusters', points: '115' },
  { team: 'AlgorithmAllies', points: '125' },
  { team: 'PixelPundits', points: '130' },
  { team: 'BinaryBrilliance', points: '140' },
  { team: 'CodeChiefs', points: '150' },
  { team: 'ByteBlasters', points: '145' },
  { team: 'CodeCrafters', points: '160' },
  { team: 'InfiniteLoopers', points: '155' },
  { team: 'DataDynasty', points: '165' },
  { team: 'TechTrailblazers', points: '170' },
  { team: 'AlgorithmArtists', points: '180' },
  { team: 'LogicLords', points: '175' },
  { team: 'DataDemons', points: '190' },
  { team: 'CodeConquerors', points: '185' },
  { team: 'TechTycoons', points: '200' },
  { team: 'CodeChampions', points: '195' },
  { team: 'TechMasters', points: '210' },
  { team: 'InnovativeTechies', points: '205' },
  { team: 'CodeCrusaders', points: '220' },
  { team: 'ByteBrigade', points: '225' },
  { team: 'CodeCreators', points: '240' },
  { team: 'TechTitans', points: '235' },
  { team: 'LogicLegends', points: '250' },
];


const deletedteams = [
  { team: 'EpicCoders', points: '60', out: '4:27' },
  { team: 'SuperCoders', points: '75', out: '4:27' },
  { team: 'PowerPlayers', points: '90', out: '4:27' },
  { team: 'CodeMasters', points: '100', out: '4:27' },
  { team: 'EliteSquad', points: '85', out: '4:27' },
  { team: 'ChampionCoders', points: '95', out: '4:27' },
  { team: 'TechWizards', points: '110', out: '4:27' },
];




export { leaderboardData, deletedteams };
